version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Saunakghosh10"
    commit-message:
      prefix: "chore"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "vitest"
      react-ecosystem:
        patterns:
          - "react"
          - "react-dom"
          - "@radix-ui/*"
