/**
 * Persona registry — 8 pixel-art founders the player can pick from
 * during onboarding. Each persona has:
 *   - a stable `id` (matches the Convex schema literal union)
 *   - a display name + tagline + archetype description for the picker UI
 *   - an accent color used for hover / active glow in the picker and for
 *     the venture HUD when this persona is active
 *   - asset paths under public/assets/personas/<id>/
 *
 * File layout expected on disk (drop PixelLab exports here):
 *   public/assets/personas/<id>/idle.png       — horizontal spritesheet
 *   public/assets/personas/<id>/walk.png       — horizontal spritesheet
 *   public/assets/personas/<id>/portrait.png   — 96×96 selection tile art
 *
 * See public/assets/personas/README.md for the full drop guide.
 */

export type PersonaId =
  | "arcanist"
  | "alchemist"
  | "artisan"
  | "drifter"
  | "oracle"
  | "engineer"
  | "healer"
  | "pathfinder";

export interface Persona {
  id: PersonaId;
  displayName: string;
  tagline: string;
  description: string;
  /** Hex accent colour used for hover glow + HUD tint. */
  accent: string;
  /** Emoji shown in tiny HUD chips when the sprite isn't loaded. */
  emoji: string;
  /** Frame counts and layout for the map spritesheet. */
  sprite: {
    /** Native frame width in the spritesheet (pixels). */
    frameWidth: number;
    /** Native frame height in the spritesheet (pixels). */
    frameHeight: number;
    /** Number of frames in the idle strip. */
    idleFrames: number;
    /** Frames-per-second for the idle animation. */
    idleFps: number;
    /** Number of frames in the walk strip. */
    walkFrames: number;
    /** Frames-per-second for the walk animation. */
    walkFps: number;
  };
  /** Public URL paths — resolved by Next.js from /public. */
  assets: {
    idle: string;
    walk: string;
    portrait: string;
  };
  /**
   * Optional extended animation set — 4-direction walk + combat states.
   * When present, the Phaser scene loads directional walk sheets + combat
   * one-shots (attack/hurt/defeat/victory) instead of the legacy 2-anim
   * (idle/walk) fallback. Only personas whose full spritesheet family has
   * been generated (e.g. Pixellab pipeline for Alchemist) set this.
   */
  extended?: {
    /** Native frame width/height for the extended set (usually 88 or 92). */
    frameWidth: number;
    frameHeight: number;
    /** Frames-per-second for each anim family. */
    idleFps: number;
    walkFps: number;
    combatFps: number;
    /** Frame counts per sheet (all sheets usually have the same count). */
    idleFrames: number;
    walkFrames: number;
    attackFrames: number;
    hurtFrames: number;
    defeatFrames: number;
    victoryFrames: number;
    /** Asset paths — one sheet per anim. Auto-derived by extendedAssetsFor. */
    assets: {
      idle: string;
      walkNorth: string;
      walkSouth: string;
      walkEast: string;
      walkWest: string;
      attack: string;
      hurt: string;
      defeat: string;
      victory: string;
    };
    /** Optional list of clip names that were NOT generated for this
     *  persona (e.g. Oracle was only partially generated by Pixellab
     *  and lacks defeat / victory / walk-* sheets). Consumers should
     *  fall back to the `idle` sheet when a listed clip is requested. */
    missingClips?: readonly (
      | "walk-north"
      | "walk-south"
      | "walk-east"
      | "walk-west"
      | "attack"
      | "hurt"
      | "defeat"
      | "victory"
    )[];
  };
}

/** Default sprite config — PRD spec: 32×48 tile, 4-frame idle @ 4fps, 6-frame walk @ 8fps.
 *  Individual personas can override any field if the PixelLab export
 *  used different frame counts. */
const DEFAULT_SPRITE = {
  frameWidth: 32,
  frameHeight: 48,
  idleFrames: 4,
  idleFps: 4,
  walkFrames: 6,
  walkFps: 8,
} as const;

/** Build the asset paths for a persona from its id. */
function assetsFor(id: PersonaId): Persona["assets"] {
  const base = `/assets/personas/${id}`;
  return {
    idle: `${base}/idle.png`,
    walk: `${base}/walk.png`,
    portrait: `${base}/portrait.png`,
  };
}

/** Build the extended-anim asset paths (Pixellab-generated pipeline). */
function extendedAssetsFor(id: PersonaId): NonNullable<Persona["extended"]>["assets"] {
  const base = `/assets/personas/${id}`;
  return {
    idle: `${base}/idle.png`,
    walkNorth: `${base}/walk-north.png`,
    walkSouth: `${base}/walk-south.png`,
    walkEast: `${base}/walk-east.png`,
    walkWest: `${base}/walk-west.png`,
    attack: `${base}/attack.png`,
    hurt: `${base}/hurt.png`,
    defeat: `${base}/defeat.png`,
    victory: `${base}/victory.png`,
  };
}

/** Alchemist's Pixellab pipeline exports 88×88 frames, 9 frames per sheet. */
const ALCHEMIST_EXTENDED: NonNullable<Persona["extended"]> = {
  frameWidth: 88,
  frameHeight: 88,
  idleFps: 6,
  walkFps: 10,
  combatFps: 12,
  idleFrames: 9,
  walkFrames: 9,
  attackFrames: 9,
  hurtFrames: 9,
  defeatFrames: 9,
  victoryFrames: 9,
  assets: extendedAssetsFor("alchemist"),
};

/** The 7 second-wave personas were generated with slightly LARGER frames
 *  (92×92 instead of the alchemist's 88×88). Everything else — 9 frames
 *  per sheet, same fps — is identical. */
function makeExtended92(id: PersonaId): NonNullable<Persona["extended"]> {
  return {
    frameWidth: 92,
    frameHeight: 92,
    idleFps: 6,
    walkFps: 10,
    combatFps: 12,
    idleFrames: 9,
    walkFrames: 9,
    attackFrames: 9,
    hurtFrames: 9,
    defeatFrames: 9,
    victoryFrames: 9,
    assets: extendedAssetsFor(id),
  };
}

/** The registry itself — order here drives the PersonaSelector grid order. */
export const PERSONAS: readonly Persona[] = [
  {
    id: "arcanist",
    displayName: "Arcanist",
    tagline: "The spellweaving strategist",
    description:
      "Casts wide vision spells over the venture map. Best for founders who love to plan every stage before the first move.",
    accent: "#8b5cf6",
    emoji: "🔮",
    sprite: DEFAULT_SPRITE,
    assets: assetsFor("arcanist"),
    extended: makeExtended92("arcanist"),
  },
  {
    id: "artisan",
    displayName: "Artisan",
    tagline: "The maker with a hammer",
    description:
      "Forges shippable prototypes at every checkpoint. Best for builders who want to ship first, polish later.",
    accent: "#f59e0b",
    emoji: "🔨",
    sprite: DEFAULT_SPRITE,
    assets: assetsFor("artisan"),
    extended: { ...makeExtended92("artisan"), missingClips: ["victory"] },
  },
  {
    id: "drifter",
    displayName: "Drifter",
    tagline: "The shadow scout",
    description:
      "Moves quietly between markets and gathers intel. Best for founders who thrive on validation before commitment.",
    accent: "#64748b",
    emoji: "🗡️",
    sprite: DEFAULT_SPRITE,
    assets: assetsFor("drifter"),
    extended: makeExtended92("drifter"),
  },
  {
    id: "engineer",
    displayName: "Engineer",
    tagline: "The tactical operator",
    description:
      "Runs the ops playbook with military precision. Best for founders shipping infra, tools, or dev-facing products.",
    accent: "#3b82f6",
    emoji: "⚙️",
    sprite: DEFAULT_SPRITE,
    assets: assetsFor("engineer"),
    extended: makeExtended92("engineer"),
  },
  {
    id: "pathfinder",
    displayName: "Pathfinder",
    tagline: "The field explorer",
    description:
      "Charts new markets and finds hidden trails. Best for founders opening spaces nobody's mapped yet.",
    accent: "#a3703a",
    emoji: "🧭",
    sprite: DEFAULT_SPRITE,
    assets: assetsFor("pathfinder"),
    extended: makeExtended92("pathfinder"),
  },
  {
    id: "oracle",
    displayName: "Oracle",
    tagline: "The visionary seer",
    description:
      "Sees five stages ahead and calls the future into being. Best for founders playing a very long game.",
    accent: "#e0d7ff",
    emoji: "🔯",
    sprite: DEFAULT_SPRITE,
    assets: assetsFor("oracle"),
    extended: {
      ...makeExtended92("oracle"),
      // Oracle was only partially generated (idle + attack + hurt).
      // Missing clips fall back to idle in the loader / combat panel.
      missingClips: ["walk-north", "walk-south", "walk-east", "walk-west", "defeat", "victory"],
    },
  },
  {
    id: "alchemist",
    displayName: "Alchemist",
    tagline: "The tinker of odd combinations",
    description:
      "Mixes weird ingredients until something works. Best for founders who love unusual, cross-domain bets.",
    accent: "#e2733d",
    emoji: "⚗️",
    sprite: DEFAULT_SPRITE,
    assets: assetsFor("alchemist"),
    // Full Pixellab pipeline: idle + 4-direction walk + attack/hurt/defeat/victory.
    extended: ALCHEMIST_EXTENDED,
  },
  {
    id: "healer",
    displayName: "Healer",
    tagline: "The compassionate builder",
    description:
      "Repairs bugs, mends teams, keeps morale high. Best for founders building for people who need care.",
    accent: "#facc15",
    emoji: "💛",
    sprite: DEFAULT_SPRITE,
    assets: assetsFor("healer"),
    extended: makeExtended92("healer"),
  },
];

/** O(1) lookup by id. */
const PERSONAS_BY_ID: Record<PersonaId, Persona> = PERSONAS.reduce(
  (acc, p) => ({ ...acc, [p.id]: p }),
  {} as Record<PersonaId, Persona>,
);

export function getPersona(id: PersonaId | null | undefined): Persona {
  if (id && PERSONAS_BY_ID[id]) return PERSONAS_BY_ID[id];
  // Sensible default — alchemist ships with the full Pixellab
  // spritesheet set (idle + 4-direction walk + combat states), so
  // unpicked users still get rich animations for the demo.
  return PERSONAS_BY_ID.alchemist;
}

export function isValidPersonaId(id: string | null | undefined): id is PersonaId {
  return !!id && Object.prototype.hasOwnProperty.call(PERSONAS_BY_ID, id);
}

/** Legacy male/female → persona fallback so pre-existing accounts get a
 *  sane default when we migrate off the old personaGender field. */
export function legacyGenderToPersonaId(
  gender: "male" | "female" | null | undefined,
): PersonaId {
  if (gender === "female") return "healer";
  return "artisan";
}
